// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans(user_id,
    name,
    starting_principal,
    yearly_interest_rate,
    monthly_payment,
    escrow_payment,
    start_date,
    duration_months,
    total_expenditure,
    total_paid,
    cost_of_credit
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, name, starting_principal, yearly_interest_rate, monthly_payment, escrow_payment, start_date, duration_months, total_expenditure, total_paid, cost_of_credit, created_at
`

type CreateLoanParams struct {
	UserID             pgtype.UUID
	Name               string
	StartingPrincipal  int32
	YearlyInterestRate string
	MonthlyPayment     int32
	EscrowPayment      int32
	StartDate          pgtype.Timestamptz
	DurationMonths     int32
	TotalExpenditure   int32
	TotalPaid          int32
	CostOfCredit       string
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.UserID,
		arg.Name,
		arg.StartingPrincipal,
		arg.YearlyInterestRate,
		arg.MonthlyPayment,
		arg.EscrowPayment,
		arg.StartDate,
		arg.DurationMonths,
		arg.TotalExpenditure,
		arg.TotalPaid,
		arg.CostOfCredit,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingPrincipal,
		&i.YearlyInterestRate,
		&i.MonthlyPayment,
		&i.EscrowPayment,
		&i.StartDate,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
		&i.CreatedAt,
	)
	return i, err
}

const getLoan = `-- name: GetLoan :one
SELECT id, user_id, name, starting_principal, yearly_interest_rate, monthly_payment, escrow_payment, start_date, duration_months, total_expenditure, total_paid, cost_of_credit, created_at FROM loans
WHERE id = $1
`

func (q *Queries) GetLoan(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoan, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingPrincipal,
		&i.YearlyInterestRate,
		&i.MonthlyPayment,
		&i.EscrowPayment,
		&i.StartDate,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
		&i.CreatedAt,
	)
	return i, err
}

const getLoansByUserID = `-- name: GetLoansByUserID :many
SELECT id, user_id, name, starting_principal, yearly_interest_rate, monthly_payment, escrow_payment, start_date, duration_months, total_expenditure, total_paid, cost_of_credit, created_at FROM loans
WHERE user_id = $1
`

func (q *Queries) GetLoansByUserID(ctx context.Context, userID pgtype.UUID) ([]Loan, error) {
	rows, err := q.db.Query(ctx, getLoansByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StartingPrincipal,
			&i.YearlyInterestRate,
			&i.MonthlyPayment,
			&i.EscrowPayment,
			&i.StartDate,
			&i.DurationMonths,
			&i.TotalExpenditure,
			&i.TotalPaid,
			&i.CostOfCredit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
