// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Username     string
	CreatedAt    pgtype.Timestamp
}
